### ISSUE TITLE
Profile pictures from Facebook do not load

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology.org#362]
URLs to profile pictures on Facebook are all broken. Facebook returns 'Content not found'

Example URL: https://fbcdn-profile-a.akamaihd.net/hprofile-ak-ash4/c178.0.604.604/s160x160/252231_1002029915278_1941483569_n.jpg

**Comment by fonglh** [comment]
The URL shows the default FB silhouette. Looks like FB has changed the URL to the silhouette photo.

The image can also be found at http://commons.wikimedia.org/wiki/File:Man_Silhouette.png
Solution will be to download this image, store it on our own server and update all the broken links with a rake task.

**Comment by fonglh** [comment]
More interesting solution is to use a random image from https://raw.githubusercontent.com/bwinton/whimsy/gh-pages/thumbnail-gifs.txt

courtesy of @jsyeo

**Comment by jsyeo** [comment]
![lol](http://coursemology.s3.amazonaws.com/file_uploads/files/000/022/566/original/66c722ed09e54825315225c9a138880d.gif?1420440354)

**Comment by wangqiang1208** [comment]
loool, finally know where do all Jason's funny gifs come from. 

I think we just put that image on our server ?  Actually might need rake task

**Comment by wangqiang1208** [comment]
Hmm, still need rake task
