### ISSUE TITLE
Order of Training tabs cannot be rearranged

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology.org#415]
![image](https://cloud.githubusercontent.com/assets/1902527/6261920/67b4b69c-b833-11e4-9346-b7c63242ab93.png)

When entries on the "Manage Tabs" modal are rearranged, the changes are not saved and the tabs are still in the original order.

**Comment by fonglh** [comment]
@wangqiang1208

**Comment by wangqiang1208** [comment]
The re-ordering of tabs were broken long time ago, probably after the refactoring of assessments. 

Is it urgent ?  I'll find time to fix this.

**Comment by fonglh** [comment]
Not really. A couple of weeks is fine
