### ISSUE TITLE
Mission emails sent out on unpublished mission

### ISSUE THREAD

**Issue by ssyberg** [Coursemology/coursemology.org#442]
I have 5 or 6 missions prepared but unpublished.  This morning emails for all of them were sent out to all of my students because today was the "start time".  I believe if a mission is marked as unpublished the start time should be ignored and emails should not be sent out.

**Comment by allenwq** [comment]
Hi Seth,

Really sorry for the trouble. 

Yes, unpublished mission should not send email notifications to student. 

This is an old issue and I have a fix for it, don't know why it happened again. Let me check and get back to you.

**Comment by allenwq** [comment]
Hi Seth, it's a bug on our side, and I just fixed it. I believe your students won't receive emails from unpublished missions anymore, sorry for the inconvenience.

**Comment by ssyberg** [comment]
No problem, thank you!
    
    On 10/7/15 12:20 PM, WANG QIANG wrote:
    
    
      Hi Seth, it's a bug on our side, and I just fixed it. I believe
        your students won't receive emails from unpublished missions
        anymore, sorry for the inconvenience. 
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by allenwq** [comment]
OK, Then I'll close this issue
