### ISSUE TITLE
Screen blacks out for a moment when switching pages

### ISSUE THREAD

**Issue by shashvatshukla** [Coursemology/coursemology.org#443]
Each time a page is opened, the entire screen just goes black for about half a second. Here is what it looks like. 

![untitled](https://cloud.githubusercontent.com/assets/7630715/10366641/61e5f614-6dfe-11e5-8ce5-9808a688af75.png)

**Comment by allenwq** [comment]
@shashvatshukla we have already fixed this issue in coursemology, but edutech doesn't belong to coursemology so that we cannot help.

**Comment by shashvatshukla** [comment]
Oh apologies for that. Thanks!

**Comment by benleong** [comment]
Hi Shashvat,

No problem. Thanks for alerting us. We're now working with Edutech to patch
it.

Warmest Regards,

Ben

**Comment by allenwq** [comment]
@shashvatshukla I'll close this issue since edutech has installed the patch.
