### ISSUE TITLE
Set course timezone?

### ISSUE THREAD

**Issue by ssyberg** [Coursemology/coursemology.org#445]
I just realized the displayed deadlines and submission times are all set to a different timezone and this is proving super confusing for myself and my students.  Would be great if I could set the timezone for the course so that these times were meaningful.

**Comment by lowjoel** [comment]
What we intend to do for this is that timezone will be coordinated, e.g. all in UTC, with the user's timezone would simply format the universally agreed time in their chosen timezone. Would that be better?

**Comment by ssyberg** [comment]
Yeah, storing UTC makes sense, as long as the display is per course.

**Comment by lowjoel** [comment]
It's not per-course, it's per-user. As an instructor, if you set it at 8pm -4UTC, and my time is set at +8UTC, I'd see 8am the following day. A user can only be in one time zone at any one point in time, right?

I think the matter at hand here is that times don't make sense between users. In this situation, if both the instructor and student are in the same time zone, he'd see the same thing. In a flipped classroom (e.g. Coursera-style classes) then this would make sense, too. A course-specific time zone doesn't seem to help that much IMO

**Comment by ssyberg** [comment]
Yeah, for an online course where students may be geographically distributed that makes a lot of sense.  My worry for per user is them having it set wrong, but I think you're right, it's much more versatile if it's per user and not per course.

**Comment by allenwq** [comment]
@ssyberg You can go to account management to change your time zone now :-P

**Comment by ssyberg** [comment]
Wow, that was fast!

**Comment by allenwq** [comment]
@ssyberg Does it work for you ? can I close this issue ? :)

**Comment by ssyberg** [comment]
Yes, looks good, thank you!

**Comment by allenwq** [comment]
OK !

**Comment by ssyberg** [comment]
May need to reopen this, I just noticed that assignment alert emails display in UTC and not in the users set timezone, again this has proven very confusing for my students.

**Comment by allenwq** [comment]
@ssyberg Noted, this is probably due to the timezone is not set in our mailing jobs.
