### ISSUE TITLE
Announcement discrepency

### ISSUE THREAD

**Issue by madsonic** [Coursemology/coursemology.org#447]
The announcements on home page and announcements page does not tally. 
From announcement page
![announcement page](https://cloud.githubusercontent.com/assets/437672/10532296/54b568c0-73ef-11e5-9c20-ae58388d2624.jpg)

From home page
![homepage](https://cloud.githubusercontent.com/assets/437672/10532297/550a3774-73ef-11e5-95eb-063092b2fe30.jpg)

**Comment by allenwq** [comment]
@madsonic Can you check the expiration dates of the announcements ?  Home page won't display those expired announcements.

**Comment by madsonic** [comment]
How do I check that? I'm not an admin, just a student

**Comment by benleong** [comment]
You can't. But it doesn't really matter does it? The announcements were made.

**Comment by madsonic** [comment]
it would mean that you have to check 2 places to be sure that no new announcements are made. if people did not know about this bug they might miss out important announcements.

**Comment by allenwq** [comment]
@madsonic No, this is not a bug, the announcements not shown on your homepage is because they have expired. Every announcement has an expiration date.
